### ISSUE TITLE
consul-k8s install fails: now can't re-install or upgrade

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#1005]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When `consul-k8s install` fails there's no way to force a helm upgrade

### Reproduction Steps

1. `consul-k8s install` with something that will error. In my example I had a previous `servicedefaults` config in a previous installation that when I uninstalled consul couldn't get deleted because the controller was gone. On a re-install the queued-up crd delete succeeded which then cause the install to fail:
```
 --> beginning wait for 45 resources with timeout of 10m0s
 ! customresourcedefinitions.apiextensions.k8s.io "servicedefaults.consul.hashicorp.com" not found
```
1. Now I'm in a situation where I have a failed install:

```
helm list
NAME  	NAMESPACE	REVISION	UPDATED                             	STATUS	CHART        	APP VERSION
consul	default  	1       	2022-01-27 13:03:41.014162 -0800 PST	failed	consul-0.40.0	1.11.2
```

But I can't re-install:

```
consul-k8s install -config-file=consul/config.yaml -namespace=default

==> Pre-Install Checks
 ! existing Consul installation found (name=consul, namespace=default) - run consul-k8s uninstall if you wish to re-install
```

Nor upgrade:

```
consul-k8s upgrade -config-file=consul/config.yaml

==> Pre-Upgrade Checks
 ✓ Existing installation found to be upgraded.
    Name: consul
    Namespace: default
 ✓ Loaded charts
 ! release: not found
```

But `helm upgrade` works:

```
 helm upgrade consul hashicorp/consul -f consul/config.yaml
Release "consul" has been upgraded. Happy Helming!
NAME: consul
```

**Comment by t-eckert** [comment]
Luke, thank you for finding the scenario. I've started working up [a test for it](https://github.com/hashicorp/consul-k8s/pull/1060) to improve the CLI functionality, but I can't get the install to fail in the same way that you do. When you get settled in next week we can take a look at it.

**Comment by lkysow** [comment]
Found an easier way to repro:

```
$ helm install consul hashicorp/consul --wait --timeout=1s
Error: INSTALLATION FAILED: timed out waiting for the condition
```

```
$ helm list
NAME  	NAMESPACE	REVISION	UPDATED                             	STATUS	CHART        	APP VERSION
consul	default  	1       	2022-03-09 14:10:04.469947 -0800 PST	failed	consul-0.40.0	1.11.2
```

**Comment by t-eckert** [comment]
A little update to this. I found that the `upgrade` command does follow the same behavior as Helm. There was a sneaky little typo in your command and the output from the CLI is confusing so I'm going to fix that.

The install behavior for Helm and the CLI is the same. I proposed adding a feature that would automatically uninstall and reinstall in that case, but we decided against it.

For the upgrade, you used the command

``` bash
consul-k8s upgrade -config-file=consul/config.yaml
```

The CLI by default will look for a Consul release in the `consul` namespace, but your failed release was in the `default` namespace. The confusing part from the CLI is that it will look up Consul deployments across all namespaces and display them, but a later function checks for the Helm deployment specifically in the provided namespace. It's that function that is giving you the error.

I am going to clarify the response to the user so that others aren't caught by the same confusing message. I'm also adding a test to ensure that we can always upgrade given that the namespace is provided.

**Comment by lkysow** [comment]
Ah good catch. Since we don't allow consul-k8s to be installed in multiple namespaces I think the CLI should look for an installation across all namespaces?

**Comment by t-eckert** [comment]
Oh yes! It does. And it finds the right installation. But [here is the bug](https://github.com/hashicorp/consul-k8s/blob/fcd0f7b5ab48c135ad4f53794afac77627e9b8ed/cli/helm/chart.go#L76). I passed in the `namespace` where I should have passed the `name` of the release.
