### ISSUE TITLE
Consul K8's pod stuck in pending state

### ISSUE THREAD

**Issue by infa-svijayak** [hashicorp/consul-k8s#1031]
Hello Team,

Am experiencing an issue in one of the consul pod which is hosted in kubernetes. The pod is stuck in pending state and the container is not getting created. When I checked the pod logs I am getting the following error
kubectl logs consul-ichs-mgmt-addon-consul-server-2 -n consul-ichs-mgmt
==> CRITICAL: Deprecated data folder found at "/consul/data/mdb"!
Consul will refuse to boot with this directory present.

I have tried deleting the pv and checked the permissions too and everything seems to be fine. Is this something you can help me with ?

**Comment by infa-svijayak** [comment]
Hello, 

I am not exactly sure on what you meant by helm config, but if you were asking about the values file and the helm chart which we are using, we are using the default helm chart provided by consul 
[consulvalues.txt](https://github.com/hashicorp/consul-k8s/files/8061540/consulvalues.txt)
Version of consul being used - 1.8.4
Version of helm being used - 3.4.1
[consulingress.txt](https://github.com/hashicorp/consul-k8s/files/8061562/consulingress.txt)
[creategossip.txt](https://github.com/hashicorp/consul-k8s/files/8061563/creategossip.txt)

**Comment by infa-svijayak** [comment]
Hello Team,

Can I get an update on this

**Comment by ishustava** [comment]
Hey @infa-svijayak 

What version of the Consul Helm chart are you using?

**Comment by infa-svijayak** [comment]
Hello,

We are using the helm chart which has the consul version of 1.8.4

**Comment by infa-svijayak** [comment]
The version of consul helm chart being used is 0.25.0

**Comment by infa-svijayak** [comment]
We pass on the gossip and tls as a secret while installing
helm install consul-<subdomain>-addon environments/ctconsul --namespace consul-<subdomain>  --set gossip="<get it from secret in existing consul Cluster>" -f ec2consul/<consul_folder>/values.yaml

**Comment by ishustava** [comment]
Hey @infa-svijayak 

I don't think I can try exactly what you've provided because it won't work with the helm chart as is. If you could provide with more detailed steps that use the official hashicorp consul helm chart repo that would be great.

Here is what I've tried. I've removed the top level `client` key and otherwise used your configuration with the helm chart 0.25.0, but did not get the error you've posted above.

Here is the values file I've tried:

```
# /tmp/config.yaml
"client":
  "enabled": false
  "extraVolumes":
  - "load": true
    "name": "consulgossip"
    "type": "secret"
  "resources":
    "requests":
      "memory": "80Mi"
      "cpu": "50m"
    "limits":
      "memory": "400Mi"
      "cpu": "150m"
"connectInject":
  "enabled": false
"dns":
  "enabled": false
"global":
  "tls":
    "enabled": true
    "verify": true
    "enableAutoEncrypt": true
    "caCert":
      "secretName": null
      "secretKey": "tls.crt"
    "caKey":
      "secretName": null
      "secretKey": "tls.key"
  "datacenter": "qa-ichs-mgmt"
  "enabled": false
  "image": "consul:1.8.4"
  "imageK8S": "hashicorp/consul-k8s:0.19.0"
"server":
  replicas: 1
  bootstrapExpect: 1
  "connect": false
  "enabled": true
  "extraVolumes":
  - "load": true
    "name": "consulgossip"
    "type": "secret"
  "resources":
    "requests":
      "memory": "80Mi"
      "cpu": "50m"
    "limits":
      "memory": "400Mi"
      "cpu": "150m"
  "storage": "10Gi"
  "extraConfig": |
    {
      "leave_on_terminate": true,
      "telemetry": {
        "prometheus_retention_time": "24h",
        "disable_hostname": true
      }
    }
"syncCatalog":
  "enabled": false
"ui":
  "enabled": true
  "service":
    "enabled": true
    "type": "ClusterIP"
```

Then I installed it like so:

```
helm install test -f /tmp/config.yaml hashicorp/consul --version 0.25.0
```

The consul server came up fine.

**Comment by ishustava** [comment]
Outside of that, I see a few issues with your configuration:

1. The secret names for certs are set to `null` which means they are not used. You've mentioned that you pass those secrets when installing, but from you values file it doesn't look like it so I thought it might be worth mentioning.
2. Does your gossip secret have agent configuration or it just the gossip key? If it's the latter, it won't work. I recommend using dedicated helm values for gossip encryption: https://www.consul.io/docs/k8s/helm#v-global-gossipencryption
3. Connect is required to be true if you're using auto-encrypt. You won't notice it for the servers, but any client joining this cluster will fail because you need connect enabled on the server to provision Consul client certificates.

**Comment by david-yu** [comment]
Hi @infa-svijayak will close this issue, since its been some time since our last response. Hope the guidance was helpful!
