### ISSUE TITLE
Consul connectInject replicas best practice

### ISSUE THREAD

**Issue by LDHo** [hashicorp/consul-k8s#1134]
#### Question
Hello, I am here to ask that whether any folks could provide a guideline on setting up the number of replicas for the connectInject in the consul helm chart ya. It would be great if someone could probably tell me a brief number on how many pods that a connect-injector could handle. Not sure whether there is any existing question which already have had answered but all I could find online so far was only mentioning the practice on scaling the consul-server cluster ya.

Hope anyone could give an advice.

Thanks.

**Comment by lkysow** [comment]
Hi Lian,
We recommend 2 replicas solely for HA in case one goes down. If you have a huge amount of pods being scheduled, then potentially you'd want more than 2 if you're seeing resource issues. But it's worth noting that although the injection is spread between the pods, the actual service registration is only done by one pod because they use leader election.

**Comment by raphlcx** [comment]
Hi, I stumbled upon this issue and would like to ask a related question.

Would it be a good idea to implement `PodDisruptionBudget` (pdb) on the connect-injector pods? Just in case the pods go down at the same time, pdb can help to ensure that there is always a replica running.

**Comment by lkysow** [comment]
@raphlcx yes that's a good idea!

**Comment by david-yu** [comment]
Closing as this question was answered. @raphlcx Please open a new issue if you wish to file the pod disruption feature request for connect injector pods.
