### ISSUE TITLE
where/how can I use consul cli?

### ISSUE THREAD

**Issue by tirelibirefe** [hashicorp/consul-k8s#1179]
Hello,
I installed Consul on Kubernetes and need to apply a policy.
I think, policies can be applied in server pod. I looked documentation but there is nothing clear for that.
When I try to create something in server pod, nothing is allowed. 

```
k exec -n consul -it consul-consul-server-1 -- sh
/ $ sudo tee vault-acl.hcl  >/dev/null <<EOF
> {
>   "key_prefix": {      
>     "vault/": {        
>       "policy": "write"
>     }
>   },
>   "service": {
>     "vault": {
>       "policy": "write"
>     }
>   },
>   "agent_prefix": {
>     "": {
>       "policy": "read"
>     }
>   },
>   "session_prefix": {
>     "": {
>       "policy": "write"
>     }
>   }
> }
> EOF
sh: sudo: not found
/ $ tee vault-acl.hcl  >/dev/null <<EOF
> {
>   "key_prefix": {
>     "vault/": {
>       "policy": "write"
>     }
>   },
>   "service": {
>     "vault": {
>       "policy": "write"
>     }
>   },
>   "agent_prefix": {
>     "": {
>       "policy": "read"
>     }
>   },
>   "session_prefix": {
>     "": {
>       "policy": "write"
>     }
>   }
> }
> EOF
tee: vault-acl.hcl: Permission denied
```

Where/how do you guys define these kind of stuff for Consul? what is the correct way to run cli of Consul?

Thanks & Regards

**Comment by blake** [comment]
You are receiving the permission denied error because the command is being executed as the `consul` user and the user does not have permissions to create `vault-acl.hcl` in the root file system.

```shell-session
/ $ whoami
consul
/ $ pwd
/
/ $ tee vault-acl.hcl >/dev/null <<EOF
{
  "key_prefix": {
    "vault/": {
      "policy": "write"
    }
  },
  "service": {
    "vault": {
      "policy": "write"
    }
  },
  "agent_prefix": {
    "": {
      "policy": "read"
    }
  },
  "session_prefix": {
    "": {
      "policy": "write"
    }
  }
}
EOF
tee: vault-acl.hcl: Permission denied
```

Instead, create the file in a directory that is writable by the `consul` user, such as the user's home directory.

```shell-session
$ cd $HOME
$ tee vault-acl.hcl >/dev/null <<EOF
{
  "key_prefix": {
    "vault/": {
      "policy": "write"
    }
  },
  "service": {
    "vault": {
      "policy": "write"
    }
  },
  "agent_prefix": {
    "": {
      "policy": "read"
    }
  },
  "session_prefix": {
    "": {
      "policy": "write"
    }
  }
}
EOF
$ ls
vault-acl.hcl
$ consul acl policy create -name=vault-acl-policy -rules=@vault-acl.hcl
```

If ACLs are enabled on your environment, you will need to first set the `CONSUL_HTTP_TOKEN` environment variable with a valid token that has permission to modify the ACL system. If you have not already created a token for your day-to-day administration of the cluster, you can use the cluster's bootstrap token. See <https://www.consul.io/docs/k8s/installation/install#acls-enabled>.

Set the value of `CONSUL_HTTP_TOKEN` to this the value returned by the previous command.

```shell-session
$ export CONSUL_HTTP_TOKEN=8d741aac-6ffc-4d95-ae2e-f14cbbe09dde
$ consul acl policy create -name=vault-acl-policy -rules=@vault-acl.hcl
```

These instructions should allow you to successfully create the ACL policy from within the Consul server. However, normally you would run these from your local machine using the `consul` CLI command. For example,

```shell-session
$ export CONSUL_HTTP_ADDR="https://$(kubectl -n consul get svc --selector app=consul,component=ui --output jsonpath='{range .items[*]}{@.status.loadBalancer.ingress[*].ip}{end}')"
$ export CONSUL_HTTP_TOKEN=$(kubectl get secrets/consul-bootstrap-acl-token --template='{{.data.token | base64decode }}')
$ consul acl policy create -name=vault-acl-policy -rules=@vault-acl.hcl
```

I hope this helps. Let us know if you have any other questions.

**Comment by maxb** [comment]
This question was also posted to https://discuss.hashicorp.com/t/where-how-can-i-define-hcl-definitions/38512 and I replied there.

**Comment by tirelibirefe** [comment]
thank you @david-yu

**Comment by tirelibirefe** [comment]
thank you @blake

**Comment by david-yu** [comment]
It looks like you found your answer from @Blake so I'll go ahead and close. Let us know if that is not the case.
