### ISSUE TITLE
hostPorts not configurable

### ISSUE THREAD

**Issue by thecodeassassin** [hashicorp/consul-k8s#1232]
#### Question

Hi,

Thanks a lot for this great helm chart. I just have a question about consul-client. Why are the ports not configurable? Now we need to scale up our cluster in order to get consul to run even though we have enough resources. We would like to be able to deploy Consul in multiple namespaces. We've managed to do it by removing the CRDs before running the chart again (there should probably also a installCRDs bool flag) but now we're running into the issue that these ports are simply not configurable.

if there are any reasons why these ports are not explicitly made available please let me know, if it's just an oversight then we can help to make a PR for this.

**Comment by lkysow** [comment]
Hi @thecodeassassin this chart does not support being installed multiple times in the same kubernetes cluster. There is a ton of automation that assumes it's only installed once. You may be able to get it to work in a fork but we don't want to encourage other users to try it, so that's why we don't support configuring the ports.

**Comment by david-yu** [comment]
Closing this issue as the previous response was provided which answer the question. Let us know if you have follow up questions!
