### ISSUE TITLE
sync adds not existing services with checks

### ISSUE THREAD

**Issue by aberfeldy** [hashicorp/consul-k8s#134]
After adding vault (3 pods, ha enabled) to our kubernetes cluster, catalog sync finds all of them and checks against the sealed status automatically, which is pretty neat. On the other hand it also adds a bunch of non existing services which all fail, because they are not on the cluster. I double checked that there aren't left over pods/services from before, all the IP's with failing checks are not used currently in the cluster. 
screenshot: https://prnt.sc/p7ly2x
I tried to deregister them via the API but they get added immediately back by the sync. The only thing in the logs is 

```
2019-09-18T07:33:50.007Z [INFO ] to-consul/sink: registering services
2019-09-18T07:34:23.762Z [INFO ] to-consul/sink: registering services
2019-09-18T07:34:57.472Z [INFO ] to-consul/sink: registering services
2019-09-18T07:35:31.201Z [INFO ] to-consul/sink: registering services
```

sync is installed with the consul helm charts using
```yaml
syncCatalog:
  enabled: true
  toK8S: false
```

Any suggestion on that, I'd like to keep catalog sync running there, but only reporting real services.

**Comment by lkysow** [comment]
Hi Andreas,
To replicate this ourselves do we just run the vault helm chart with
```yaml
  ha:
    enabled: true
```
?

**Comment by aberfeldy** [comment]
Morning,
yes, the rest are standard settings (besides backend which is consul)

**Comment by lkysow** [comment]
Hi Andreas,
Since you're running `syncCatalog` with `toK8S: false`, `consul-k8s` shouldn't be creating any services in Consul. In fact, when `consul-k8s` creates services, it always registers them with a node called `k8s-sync`. Since your nodes are called `cluster-worker-{n}` this shows me that these service instances are not being created by `consul-k8s`.

What you're likely seeing is Vault registering itself with Consul which it does automatically:

> inclusion of this backend will also register Vault as a service in Consul with a default health check.
https://www.vaultproject.io/docs/configuration/storage/consul.html

Are you using the `vault-helm` chart here: https://github.com/hashicorp/vault-helm? If so, it's probably best to open up an issue there. Sorry I can't help you further.

**Comment by aberfeldy** [comment]
Hey Luke, 
can confirm, it was vault not consul. After recreating it (yes, using the helm charts), everything was as intended,, probably some vault instances were zombieing around.
Thanks for the effort.
