### ISSUE TITLE
connect sidecar add healthcheck in annotation

### ISSUE THREAD

**Issue by Veres72** [hashicorp/consul-k8s#146]
Now, consul sidecar check services through ip:port. If service listening port, but don't have success probe, consul direct traffic in the dead pod. 
Add some annotations such as: 
```"consul.hashicorp.com/service-check": "http://127.0.0.1:8080/ping/serice/alive':10s"     ```

May be here add checks

https://github.com/hashicorp/consul-k8s/blob/8b83fd98f2bbaeed810954bc9a7298db1efe4d14/connect-inject/container_init.go#L245-L261

example:
```
  checks {
    name = "{{ .ServiceName }} check"
    http = "{{ .checkPath }}"
    interval = "{{ .checkIntervas }}"
  }
```

**Comment by lkysow** [comment]
Hi all, with the release of consul-helm 0.26.0 we support syncing kube readiness status to Consul. So instead of setting checks via annotations in the PR can you try creating kube readiness probes? That way Consul and Kube will agree on the readiness status.

If that works we will close this issue, however if there's a reason that that won't work please let us know.

**Comment by Veres72** [comment]
Hi. 
Unfortunately I don't have opportunity to check it. I think you can close a issue.
