### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by puzhengwu** [hashicorp/consul-k8s#1496]
k8s 1.18.20

kubectl get all -A|grep consul
consul                 pod/consul-client-cg8pv                                            0/1     Running            0          7m58s
consul                 pod/consul-client-glkmr                                            0/1     Running            0          7m58s
consul                 pod/consul-client-tz2dt                                            0/1     Running            0          7m58s
consul                 pod/consul-client-znndg                                            0/1     Running            0          7m58s
consul                 pod/consul-server-0                                                0/1     Pending            0          7m58s
consul                 pod/consul-server-1                                                0/1     Pending            0          7m58s
consul                 pod/consul-server-2                                                0/1     Pending            0          7m58s
consul                 service/consul-dns                                         ClusterIP      10.96.99.165    <none>        53/TCP,53/UDP                                                                                               7m58s
consul                 service/consul-server                                      ClusterIP      None            <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP                                     7m58s
consul                 service/consul-ui                                          ClusterIP      10.96.207.184   <none>        80/TCP                                                                                                      7m58s
consul        daemonset.apps/consul-client        4         4         0       4            0           <none>                   7m58s
consul           statefulset.apps/consul-server        0/3     7m58s

kubectl describe pod/consul-server-0 -n consul
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  4m15s  default-scheduler  0/5 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 4 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  4m15s  default-scheduler  0/5 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 4 pod has unbound immediate PersistentVolumeClaims.

**Comment by kschoche** [comment]
Hi @puzhengwu  - 
Thanks for filing this issue, and I'm sorry you're having trouble with running Consul.
So that we can help you, could you please follow the Bug submission guideline, including steps to reproduce and information about the problem and your environment.
Thanks!

I've copied and pasted it below:



### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.



---



### Overview of the Issue



### Reproduction Steps



### Logs



### Expected behavior



### Environment details




### Additional Context

**Comment by david-yu** [comment]
Closing as no details were given.
