### ISSUE TITLE
When consul-k8s chart will support k8s v.1.25?

### ISSUE THREAD

**Issue by ZiaUrRehman-GBI** [hashicorp/consul-k8s#1577]
#### Question
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
As PodSecurityPolicy is removed in v.1.25 and in your helm chart too many place this resource is added
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
when you have plan to remove this from helm chart and provide support for k8s v.1.25 version?

**Comment by david-yu** [comment]
@ZiaUrRehman-GBI I'm curious do you plan on running Consul K8s on just 1.25 or will you be deploying on other version as well? I ask because we'll likely need to think about supporting 1.24 and below also using PSA only or providing support for both PSA and PSP on 1.24 and below. If you do plan on running Consul K8s on 1.24 and below I'm curious if PSA or PSPs will be used.

**Comment by ZiaUrRehman-GBI** [comment]
I believe support should be added for both using if with capabilities.Api.has feature of Helm.

**Comment by darkn3rd** [comment]
There is a way to detect the version of the API and template the correct manifests in Helm, but care is needed not to break debugging and dry-runs.

**Comment by david-yu** [comment]
Closing as this should now be addressed via Consul K8s 1.2.1, 1.1.4, and 1.0.9.
