### ISSUE TITLE
consul connect inject register service slow

### ISSUE THREAD

**Issue by hardme** [hashicorp/consul-k8s#1861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When the number of pods is too large（80 pod）, it takes a long time for the sidecar to find the service registered in consul when the pod starts，The first batch of pods (40) register on consul very quickly (around 4 minutes), but the second batch of pods (40) is very slow (around 20 minutes)

**Comment by curtbushko** [comment]
Hello @hardme,

Thanks for sending in a question! I've seen two scenarios where service registration can look slow.

1) If your services have dependencies on other services. For example, if service A depends on B which depends on C (A -> B -> C), then service A will not be healthy and registered until it's downstream dependencies (B, C) are healthy. In this case, I usually recommend that your deployments are split up and C is deployed first and separately.

2) Your Kubernetes cluster is starved for resources. If pods are taking a while to start and become healthy, then registration will be slow. Consul-k8s has controllers that are watching for Kubernetes Services and Pods to be created and then we register those services with Consul. I believe you can increase the resources for `connectInject.resources` in your values.yaml file and that may help with that controller.

In general, we set the default resource values in the helm chart to be very low so that Consul on Kubernetes can be run everywhere with ease.

**Comment by hardme** [comment]
I'm sorry, maybe I didn't describe it clearly. It's my pod's initContainer that looks for the consul service very slowly.
The longest waiting time is to cause the container to fail to start
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/41999237/215921988-969789d6-0221-4811-93f0-b537179f2f85.png">

**Comment by hardme** [comment]
I adjusted the memory of consul-connect-inject from 300M to 1G, and this problem was solved
