### ISSUE TITLE
Feature request: Use iptables to make local proxies more transparent

### ISSUE THREAD

**Issue by krancour** [hashicorp/consul-k8s#23]
In a similar vein to #22, I'd be interested in seeing options to make pods less aware of Consul.

I've noticed that Istio uses iptables rules to force all of a pod's inbound and outbound traffic through the proxy sidecar.

Utilizing an approach such as this means clients don't need to be explicitly reconfigured to talk to the local proxy and severs don't need to be reconfigured to bind to 127.0.0.1 instead of 0.0.0.0. Effectively, both would happen transparently, courtesy of iptables.

Combined with #22, my hope would be that applications could be packaged (e.g. as a Helm chart) with zero awareness of Consul and an _operator_ can choose to enforce the use of Consul as a matter of policy.

**Comment by mitchellh** [comment]
This is the plan (roughly). I'll cc @banks onto this issue who is helping in part to think of the future here.

**Comment by banks** [comment]
As background here for anyone passing through, we want Connect to work on all platforms which is why focus initially is on core features that make no assumptions about OS/Network/Platform. Now that's built we plan to build increasingly rich tooling and integrations for strategic platforms to make stuff like this cleaner and more magical!

Transparent proxy via IP tables is relatively easy in Kube since the infrastructure to install it is there and the OS/Container/network model is fairly prescriptive.

We're still nailing down the priorites/road map for next few months here so no specific news other than this is on our wishlist too!

**Comment by patoarvizu** [comment]
In the meantime, are there any suggested workarounds/patches? Is it possible at least to have a single local port that upstream requests can be routed through? Can anything like this be done with some [Envoy advanced configuration](https://www.consul.io/docs/connect/proxies/envoy.html#advanced-listener-configuration)?

Also, does this mean that until this is done, ingresses won't work? I can annotate the ingress controller to get the sidecar injected and get its service registered, but how will the controller know to go "upstream" via 127.0.0.1?

**Comment by banks** [comment]
> Is it possible at least to have a single local port that upstream
requests can be routed through?

Not currently because Connect is only proxying L4 right now so the only way
it can distinguish between requests for different upstreams is different
listeners on different ports. L7 support which will enable a single
listener (assuming all your services are HTTP/gRPC) is in the works.

Envoy supports "transparent proxy mode" which could potentially be used in
conjunction with IP tables - that is part of what this issue represents.
The actual changes might not be super hard and Connect supports passing
through custom Envoy config which you can do via the API even though the
injector currently doesn't have a good way to add this via annotations. See
the Connect Envoy docs for more info.

> Also, does this mean that until this is done, ingresses won't work?

Depends on which ingress you are using and how you are configuring it, but
yes likely none of them work out of the box. We are working with existing
"ingress" providers to figure out what the cleanest integration we can make
for those is without re-inventing the whole problem space over again. In
theory it's not hard for us to just write Some Envoy config and make an
ingress work, but making it work well in the existing eco-system requires
more thought.

If you are interested in trying to get something working for either
problem, we'd be interested to see how you get on. Both of these things are
being worked on but no definite timelines!

Thanks

**Comment by sh0rez** [comment]
Now that's L7 support is there (https://www.consul.io/docs/connect/l7-traffic-management.html), any updates on this?

**Comment by lkysow** [comment]
> Now that's L7 support is there (https://www.consul.io/docs/connect/l7-traffic-management.html), any updates on this?

Hi @sh0rez the L7 support is for traffic management policy right now and we haven't yet done any additional work to change how you use Connect in Kubernetes.

**Comment by david-yu** [comment]
Hi everyone, we have released Transparent Proxy support in the Consul 1.10 beta and is now deployed by the [0.32.0-beta](https://github.com/hashicorp/consul-helm/releases/tag/v0.32.0-beta1) Consul Helm Chart. Please give this a try and provide feedback if you can. I'll close this issue, as you should be able to file follow on issues after evaluating the beta.
