### ISSUE TITLE
Add support ARM arch

### ISSUE THREAD

**Issue by kamontat** [hashicorp/consul-k8s#256]

**Comment by ishustava** [comment]
Hey @kamontat, we already have `linux_arm64` binaries in [our releases](https://releases.hashicorp.com/consul-k8s/0.14.0/). Does this binary not work for you?

**Comment by kamontat** [comment]
I didn’t see on docker hub digest, where did you deploy arm arch?  

https://hub.docker.com/r/hashicorp/consul-k8s/tags

**Comment by lkysow** [comment]
Hi Kamontat, you're correct, we don't build an arm Docker image. We'll look into it.

**Comment by alvin-huang** [comment]
Hi @kamontat I had to do some digging to figure out how to do this properly, apologies for the delay. I added an enhancement to our build process and pushed up the latest release of `consul-k8s` for ARM here: https://hub.docker.com/repository/docker/hashicorpdev/consul-k8s. Would you be able to try this out to make sure it suits your needs? If it does, I can merge my change into master in our build pipeline and it will build this way on the next release.
 
You should be able to either pull the `latest` or `0.14.0` tag and have docker pick the correct image based on your architecture. I am thinking of removing the `version-$arch` tags since they aren't really needed but for now that would have to be a manual process since the Dockerhub API doesn't allow tag deletion [without an account with 2FA OFF ](https://github.com/docker/hub-feedback/issues/1927).

Please let me know if this works for you!

**Comment by blake** [comment]
@alvin-huang, I just tested this and it appears the `consul-k8s` binary is missing from the ARM version of the image.

```shell
$ ctr run --rm --tty docker.io/hashicorpdev/consul-k8s:0.14.0 consul-k8s-test uname -m
armv7l
$ ctr run --rm --tty docker.io/hashicorpdev/consul-k8s:0.14.0 consul-k8s-test
/bin/sh: /bin/consul-k8s: not found
```

The binary is present in the version for amd64.

```shell
$ docker run --rm -it hashicorpdev/consul-k8s:0.14.0 uname -m
x86_64
$ docker run --rm -it hashicorpdev/consul-k8s:0.14.0
Usage: consul-k8s [--version] [--help] <command> [<args>]

Available commands are:
    acl-init                Initialize ACLs on non-server components.
    delete-completed-job    Delete Kubernetes Job when complete.
    get-consul-client-ca    Retrieve Consul client CA if using auto-encrypt feature.
    lifecycle-sidecar       Connect lifecycle sidecar.
    server-acl-init         Initialize ACLs on Consul servers and other components.
    service-address         Output Kubernetes Service address to file
    sync-catalog            Sync Kubernetes services and Consul services.
    version                 Prints the version
```

**Comment by cerebrate** [comment]
I'm trying to do the same thing as @blake on my Raspberry Pi cluster and suffering the same error; consul-k8s not found.

**Comment by alvin-huang** [comment]
Thanks for the report! looking into this today...

**Comment by alvin-huang** [comment]
The issue here stemmed from https://github.com/hashicorp/consul-k8s/issues/263. The ARM binaries were misnamed so when they were added to `/bin` in the ARM container, it was actually called `project` and not `consul-k8s` this is fixed now in our build process and I have also rebuilt the containers.

Would you all be able to take a look at the new ones: https://hub.docker.com/repository/docker/hashicorpdev/consul-k8s? 
```
$ docker run hashicorpdev/consul-k8s:0.14.0-arm64v8 /bin/sh -c "uname -m && consul-k8s version"
aarch64
consul-k8s v0.14.0
$ docker run hashicorpdev/consul-k8s:0.14.0-arm32v6 /bin/sh -c "uname -m && consul-k8s version"
armv7l
consul-k8s v0.14.0
```

**Comment by blake** [comment]
Working now, @alvin-huang! 😄

**Comment by cerebrate** [comment]
Works great for me now, too! 😂

**Comment by alvin-huang** [comment]
To close the loop on this, I merged the changes in our build pipeline so you should see multiarch builds from the next version of `consul-k8s` forward. Cheers!
