### ISSUE TITLE
Registering different tags per instance in services.

### ISSUE THREAD

**Issue by soonoo** [hashicorp/consul-k8s#425]
#### Question
Tags can be added to service via `consul.hashicorp.com/service-tags` annotation.  
How can I add a tag for specific instance that service contains?

For example, when `api-server-service` load balances traffics to three pods(`api-server-pod0`, `api-server-pod1`, `api-server-pod1`),  is it possible to add `server0` tag to `api-server-pod0` instance and `server1` tag to `api-server-pod1`?

**Comment by ishustava** [comment]
Hey @soonoo, 

In general, I don't think so. That is because on Kubernetes annotations apply to all pods in a deployment/replicaset/statefulset etc, not the individual pods. However, for the use-case you're describing, we already [add](https://github.com/hashicorp/consul-k8s/blob/4ef6eb8e9292d5e0b829899ceea7cc7d749cd1e7/connect-inject/container_init.go#L284) pod name as metadata to each instance with key `pod-name`, so that should work. 

Hope this helps!

**Comment by david-yu** [comment]
Hi @soonoo we're going to close this one as we have not seen a response. We hope his answered your question, if not please feel to re-open if its the same issue.
