### ISSUE TITLE
yaml files

### ISSUE THREAD

**Issue by SunChero** [hashicorp/consul-k8s#471]
Hello,
can you please support or provide yaml files (as examples) for those who try to stay away from helm as much as they can.

thank you

**Comment by david-yu** [comment]
HI @SunChero we do occasionally see feedback that folks want to utilize Kube YAML manifests instead. You should be able to use `helm template` [docs](https://helm.sh/docs/helm/helm_template/) as a way to generate such manifests on your own, although we do realize it will mean you need to utilize the helm CLI. It will be tricky for us to supply such files since we use templating for configuring a lot of different values that are interpolated to generate Kube YAML files. Sorry if that is not the answer you were looking for, but we hope you understand. 

Generate Kube YAML files
```
helm template \
  --values ./values/values.yaml \
  --output-dir ./manifests \
    ./charts/consul-helm
```
Run kubectl apply to apply the manifests
```
kubectl apply --recursive --filename ./manifests/consul-helm
```

**Comment by lkysow** [comment]
In addition, we rely on [Helm hooks](https://helm.sh/docs/topics/charts_hooks/) for functionality around:
* ACLs
* TLS
* Federation

These hooks require helm to be driving the install. So if you're using these features then you must use helm, not helm template.
