### ISSUE TITLE
Catalog Sync: Consul blocking loops are not tolerant of the usual edge cases

### ISSUE THREAD

**Issue by banks** [hashicorp/consul-k8s#54]
The Consul blocking loops in the catalog syncer didn't re-use `consul/watch` so have a number of common flaws:

 - No rate limiting - in case where services churn in Consul, the catalog sync becomes a 100% CPU burn loop. I suggest following the pattern we've done in recent implementations of blocking where we use a `rate.Limiter` to prevent making too many requests.
 - Intolerant of index going backwards. This can happen in come cases - notably KV lists, but more generally if the state is ever restored from a snapshot. The correct logic is to detect it and reset the loop index to zero (effectively start again).
 - While not technically required, it's nice to protect against a (buggy) Consul endpoint ever returning a 0 `MinIndex` which causes a 100% CPU burn loop. It's always safe to check if index is <0 after the request is done and if so set it to 1 instead.

**Comment by david-yu** [comment]
Hi @banks thanks for filing. A lot has changed since you filed this issue! I'll go ahead and close this issue as we're likely not going to make significant changes to the catalog sync design in the future. For those who have stumbled on this issue, please feel free to file a PR if you do find a solution to any of one problems described above that you would like to share. Thank you!
