### ISSUE TITLE
Make Consul client ports customizable for connect-inject init container

### ISSUE THREAD

**Issue by karras** [hashicorp/consul-k8s#544]
#### Feature Description

This feature request is related to what is described in the [consul-helm issue #997](https://github.com/hashicorp/consul-helm/issues/997). Basically in certain environments `hostPorts` are not available and thus the currently only feasible replacement are `nodePorts`. By using `topologyKeys` (K8s < 1.21) or `Topology Aware Hints` (K8s 1.21+) the `nodePort` loadbalancing can be prevent in order to enforce that the inject sidecars establish connectivity to their node-local Consul client.

In order to avoid having to extend the `service-node-port-range` to include the `85XY` ports, the hardcoded Consul client ports in consul-k8s should be customizable.

#### Use Case(s)

* Environments where `hostPorts` are not available, make it possible to evade to `nodePorts`
* Provide more flexibility by making the hardcoded ports customizable

#### Contributions

We (@flavioaiello, @pree & @karras) are already working on a PR.

**Comment by david-yu** [comment]
Hi @karras Although we currently only support hostPorts until our architecture will no longer require us from doing so, this is something that we are wary of supporting due to our assumption that we use well known host ports across all Consul Kubernetes clusters.

Adding configurable host ports causes an increase in complexity for all of our tests and all of our features going forward since we will need to test with the default ports and with custom configured ports. This will also increase complexity for a large upcoming feature around supporting a multi-tenant service mesh.

We will leave this PR up so that others may find this work useful. It may also be possible that this could be used in the interim to migrate to additional environments that do not have full host port support. We will provide some feedback next week as well on the PRs that were linked in this issue.

**Comment by karras** [comment]
Thanks for the review and additional inputs, much appreciated! As discussed it can't be merged. Thus I'm closing this and the other related PRs and issues to prevent cluttering and prepare for the upcoming repo consolidation into consul-k8s.
