### ISSUE TITLE
If two Services select the same pods then pods won't start

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#592]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

If two kube services have the same selector of mesh pods then Consul will register 4 service instances (two for each pod, sidecar and app) and then connect-init will loop forever because it's waiting for exactly 2 service instances.

### Possible solutions

We can't register two service instances for one pod because the pod's sidecar can only receive traffic for one service name. So I think we need to provide a way to exclude one of the services from syncing. I checked and if you label the service, the labels are available at the endpoints level so we could do something basic like:

```
labels:
  consul.hashicorp.com/connect-ignore: true
```

**Comment by chauhanshubham** [comment]
Hello, any further updates on this? I'd like to implement it :)

**Comment by david-yu** [comment]
@chauhanshubham Could you tell me more about why you would need this particular feature? In this case we are ignoring one of the services via a label. Are you also looking to deploy something like NGINX Ingress controller with Consul K8s sidecar proxies?

**Comment by chauhanshubham** [comment]
hi @david-yu i was just looking at it as a good first issue. Since the connect-init loop seems to get stuck in this scenario, I thought it should probably get fixed, irrespective of any specific usecases.

**Comment by mike-code** [comment]
@david-yu Actually I exactly have a case with nginx. My understanding is that having nginx with sidecar proxy is a valid scenario because otherwise I won't be able the to allow the nginx's loadbalancer service to communicate with applications that have sidecar proxies enabled.

Nginx deployment deploys two services `nginx-controller` and `nginx-controller-admission` (one being of type `LoadBalancer` and the other of `ClusterIP`) and both are bound to the same deployment. What would be the right way  of dealing with such scenarios?

**Comment by david-yu** [comment]
@mike-code We will be releasing the functionality that addresses this issue in our next release most likely around mid-December. Stay tuned!

**Comment by markharding** [comment]
> @mike-code We will be releasing the functionality that addresses this issue in our next release most likely around mid-December. Stay tuned!

@david-yu any update on this?

**Comment by ishustava** [comment]
Hey @markharding the fix for this was released, and you can now add the `consul.hashicorp.com/service-ignore` label to your service as mentioned in #858. If you are still running into issues using the latest release of the helm chart, please create a new issue and describe the steps for us to reproduce. Thanks!
