### ISSUE TITLE
Support for synchronizing kubernetes resources between clusters

### ISSUE THREAD

**Issue by ajbouh** [hashicorp/consul-k8s#6]
First, apologies if this request is out of scope for the current project!

I'm working on a project that creates kubernetes resources in response to user actions. I'd like to use consul to synchronize some of these resources between clusters. Is something like this possible with the current release?

**Comment by mitchellh** [comment]
This is currently possible, but this is planned functionality. If you have a central Consul cluster (runnning in or out of K8S), it should be possible to sync `K8S_1 => Consul => K8S_2`. There are obviously a lot of complexities around making sure the networking is configured properly to both 1.) make the sync possible and 2.) make the services routable.

No timeline, and no commitment we'll even do it yet, but keeping this issue open since we're still discussing.

**Comment by lkysow** [comment]
Hi Adam,
I think we'd only look to sync services because we want consul-k8s to be focused on service mesh so I'm going to close this for now. I think there are likely external solutions for syncing CRDs between Kubernetes clusters.
