### ISSUE TITLE
helm: Support a pre-set bootstrap ACL token

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Description 

We currently support the following use case with Consul K8s: 

If I have a Consul cluster, I can manually bootstrap ACLs and extract the boostrap token into a Kubernetes secret (i.e. create a Kubernetes secret manually after `consul acl bootstrap`). 

However, the following use case is what this feature request is tracking: 

I don't have a Consul cluster yet and I want to start one with bootstrap token defined via a String value. Could we support setting the master token ahead of time prior to the installation? For example if `global.acls.bootstrapToken` was set to a secret we would use the value in the secret.

**Comment by david-yu** [comment]
Closing as this is partially addressed via https://github.com/hashicorp/consul-k8s/pull/1061, where Vault is used as the secrets backend to specify a ores-set bootstrap ACL token. This support was built for Vault since setting a pre-set bootstrap token via String is what works well with a KV secrets engine like Vault. If a more generic solution is needed please re-open a new issue.
