### ISSUE TITLE
helm:Support expose DNS port 8600 with consul agent DaemonSet

### ISSUE THREAD

**Issue by carrypann** [hashicorp/consul-k8s#662]
As official document says:
> The client agents are run as a DaemonSet. This places one agent (within its own pod) on each Kubernetes node. The clients expose the Consul HTTP API via a static port (8500) bound to the host port. This enables all other pods on the node to connect to the node-local agent using the host IP that can be retrieved via the Kubernetes downward API. See accessing the Consul HTTP API for an example.

I deploy a kubenetes Service to run openrestry as gateway, and the openrestry is expected to route to backend microservice by dns, but consul client agent pod didn't expose DNS port(8600) to bound to host port.
So is there a solution to expose agent DNS port? Or any other better way to lookup dns?

**Comment by david-yu** [comment]
Closing since as we will be removing client agents and host ports altogether as that has provided challenges when deploying Consul Service Mesh on managed runtimes like EKS Fargate and GKE Autopilot. I would suggest directly talking to Consul severs instead if you are looking to utilize Consul DNS.

**Comment by david-yu** [comment]
@raphlcx We currently don't support running Consul K8s on Fargate because as you said daemonsets are not supported as are HostPorts. So yes removal of client agents will support the Fargate use case and we are tracking towards providing a solution towards the end of the year. This requires a large architecture change which is why it has taken so long to come to fruition. Please feel free to open up a new issue but we are tracking this internally right now.

**Comment by raphlcx** [comment]
Thanks for the confirmation, @david-yu. Looking forward to hearing Fargate support soon.
