### ISSUE TITLE
helm:support for sidecar containers & initContainers via extraContainers &extraInitContainers

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-k8s#682]
Right now there's no support for sidecar containers which forces certain processes to live outside of kubernetes, ie TLS cert initialization & refreshing.

The addition of a values extraContainers and extraInitContainers (matching the standard of stable helm charts) would ease this. 

For the example of TLS certs, this would enable users to initialize and share certs via a shared emptyDir volume instead of being forced to persist certs in a (read-only from kubernetes jobs/containers) K8s Secret

**Comment by david-yu** [comment]
Although we have not implemented support for extraInitContainers, we now have the ability to utilize extraContainers to deploy sidecars onto clients and servers: https://github.com/hashicorp/consul-k8s/pull/749. 

I am closing now since this is a really old issue. Please file a new issue if extraContainers is still needed. Thank you!
