### ISSUE TITLE
Require one service account for all service mesh enabled applications in k8s cluster

### ISSUE THREAD

**Issue by ashwinkupatkar** [hashicorp/consul-k8s#694]
Hello Team,

Based on https://discuss.hashicorp.com/t/one-service-account-for-all-service-mesh-enabled-application-services-in-k8s-cluster/28734/4

We need to have a capability to use just one service account for all the services using service mesh when they are deployed on k8s where consul ACLs are enabled.

Reason being having 1000s of services using service mesh means 1000s of service accounts … and its quite a deal to manage them from the k8s administration perspective... 

-Ashwin

**Comment by ashwinkupatkar** [comment]
Lets say, we can try to have one service account per k8s namespace.

**Comment by abhiTamrakar** [comment]
Just thinking out loud: As I understand from this issue https://github.com/hashicorp/consul-helm/issues/202, the reason behind having the mandate for service account name = first container or annotation in the pod to help it infer the ACL token names based on service account for that pod because there could be more than just "default" service account and it could make it complex to identify which one to use for an automated solution like consul mesh.

The challenge is, if there are too many service accounts with each pods:
- It is mostly just overhead to maintain one service account per pod for the sake of naming for the ACL token. ref: one of the files I found relevant https://github.com/hashicorp/consul-k8s/blob/b5d2de83eb5c6c98a216e5fb9d28a9a454ae1a97/control-plane/subcommand/server-acl-init/command.go#L587 (I could be wrong, if so please correct me)
- If at some moment there is a hard need to rotate pub keys that signed service account token this becomes more challenging and people will have no solution but to replace cluster (I know most folks would say replace is what it will need but there can be a way to rotate them on existing clusters as well).

I am sure some of the users can get around with choice of annotations but then its a tradeoff that they miss enabling mesh for all apps by default.

I do agree its a simple approach if service account name = service name, to get details without firing more get request, and its not easy to solve this problem but somewhere it has to be taken in terms of security of the clusters as well because besides rotating tokens, there could be some service accounts may need more privileges, so inherited by their tokens.
