### ISSUE TITLE
Consul k8s create a lot of tokens

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/consul-k8s#845]
Hello guys, as I got no luck on [discuss](https://discuss.hashicorp.com/t/consul-k8s-create-a-lot-of-tokens/31457), I'm opening this here. 

I have my consul servers 1.10.3 with ACL enabled.
My consul k8s talk to the consul servers via consul-k8s-auth-method to retrieve token when a new pod is started in order to be used into envoy configuration.

I noticed that everytime a new pod is created, a new token is also created.
It turns out that I was have 12XX token created at some point :smile: .
So on my 1st test I decided to create the appropriate ACL policy and bind the freshly created token with it.
Unfortunately, new tokens where created no matter what.
I finally noticed that token are created with the option "AuthMethod": "consul-k8s-auth-method", and that’s why any pods were not fetching the right token event if AuthMethod wasn’t referenced here [ACL System | Consul by HashiCorp](https://www.consul.io/docs/security/acl/acl-system#acl-tokens).

So I tried to create a the token with this option but I’ve been rejected!

`AuthMethod field is disallowed outside of Login`

Following the documentation here [https://www.consul.io/docs/security/acl/auth-methods](https://www.consul.io/docs/security/acl/auth-methods):

**Applications SHOULD use the consul logout subcommand or the logout API endpoint to destroy their token when it is no longer required.**

From my perspective, in the log of the pod, yes I saw many times:

`my-dummy-pod-xxxx consul-connect-inject-init 2021-11-03T14:36:33.045Z [INFO]  Consul login complete
my-dummy-pod-xxxx consul-connect-inject-init 2021-11-03T14:36:33.146Z [INFO]  Registered service has been detected: service=my-dummy-pod
my-dummy-pod-xxxx consul-connect-inject-init 2021-11-03T14:36:33.146Z [INFO]  Registered service has been detected: service=my-dummy-pod-sidecar-proxy
my-dummy-pod-xxxx consul-connect-inject-init 2021-11-03T14:36:33.146Z [INFO]  Connect initialization completed
my-dummy-pod-xxxx consul-connect-inject-init     Successfully applied traffic redirection rules`

but for sure I never saw any:
`my-dummy-pod-xxxx consul-connect-inject-init 2021-11-03T14:36:33.045Z [INFO]  Consul logout complete`

and the the token being deleted on consul servers.

So my questions are:
* if there any fixes coming to clean unused tokens?
* is there a way that all my pods for 1 service are using the same token?

From my design, I have for the service A:
* ACL policy
* ACL token
Service B will never use token from service A.

The funny thing is, the ACL I created is used by the token created by consul-k8s* components.

Is it a best practice to have 1 token for 1 service or it’s better to have 1 token per pod.
If we have 100 pods for a service, we will have 100 token so I’m not sure if it’s a best practice.

Waiting for your answers.

**Comment by lkysow** [comment]
Hi, what version of consul-k8s are you running? We implemented a fix for token cleanup in 0.33.0.

**Comment by Lord-Y** [comment]
@lkysow I'm using `hashicorp/consul` chart version `0.34.1`.

**Comment by Lord-Y** [comment]
@lkysow any feedback?

**Comment by lkysow** [comment]
Can you please provide the following information from our bug issue template (https://github.com/hashicorp/consul-k8s/issues/new?assignees=&labels=bug&template=bug_report.md).

In addition, I'm wondering if you're using our ACL automation or you're somewhat rolling your own? As you can see in the below video, the ACL tokens are getting cleaned up:

https://user-images.githubusercontent.com/1034429/141598751-ba894e34-2ee5-4a83-8f32-b0b3cf8928d9.mp4


### Reproduction Steps


In order to effectively and quickly resolve the issue, please provide exact steps that allow us the reproduce the problem. If no steps are provided, then it will likely take longer to get the issue resolved. An example that you can follow is provided below. 

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  domain: consul
  datacenter: dc1
server:
  replicas: 1
  bootstrapExpect: 1
connectInject:
  enabled: true
controller:
  enabled: true
```
1. View error

### Logs


Provide log files from Consul Kubernetes components by providing output from `kubectl logs` from the pod and container that is surfacing the issue. 

<details>
  <summary>Logs</summary>

```
output from 'kubectl logs' in relevant components
```

</details>


### Environment details


Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.22.x
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): EKS, AKS, GKE, OpenShift (and version), Rancher (and version), TKGI (and version)
- Networking CNI plugin in use: Calico, Cilium, NSX-T 

Any other information you can provide about the environment/deployment.

**Comment by Lord-Y** [comment]
Hello @lkysow ,

Sorry for the very late answer.
I'll close this issue. I cleaned everything I did and reinstall my consul k8s (chart 0.34.1). Everything is working and in the logs I saw:

`consul-connect-injector-webhook-deployment-cf475b845-6ksw8 sidecar-injector 2021-12-01T00:22:37.263Z    INFO    controller.endpoints deleting ACL token for pod      {"name": "xxxxxx"}`

Thx.

**Comment by rdxmb** [comment]
I'm just wondering about not deleted tokens in my consul-cluster. We cannot make sure that there is a `consul logout` in any case, see https://github.com/hashicorp/consul-k8s/issues/1441 for examples.

Do we need to configure a TTL to get the tokens cleaned up? The default auth method `consul-k8s-component-auth-method` does not have a TTL defined. So we are thinking about creating a new auth method with a short TTL. 
Is this the way to go?
