### ISSUE TITLE
Having Consul accept more than 1 service pointing to a pod with connect inject

### ISSUE THREAD

**Issue by mike-code** [hashicorp/consul-k8s#849]
#### Question

This issue is related to https://github.com/hashicorp/vault-helm/issues/574

Is it possible to have multiple services pointing to the same pod and use connect inject at the same time? The issue mentioned above from `vault-helm` repository shows that if there are two `Service` resources (ie. headless and "regular") pointing to the same `Pod`, then sidecar won't inject due to having too many services.

I've encountered the same problem with [Redis chart](https://github.com/bitnami/charts/tree/master/bitnami/redis) which also uses headless Service.

### Logs

<details>
  <summary>Logs</summary>

```
Timed out waiting for service registration: error="did not find correct number of services: 4"
```

</details>

**Comment by mike-code** [comment]
Closing as a duplicate of https://github.com/hashicorp/consul-k8s/issues/592

**Comment by lkysow** [comment]
RE https://github.com/hashicorp/vault-helm/issues/574#issuecomment-963408092

>For me personally (not limited to Vault) because I don't know what I want or don't want registered in the Consul mesh so I register everything.

>Actually this question could be extended to whether Consul is useful in single k8s cluster at all (with no multi cluster, multi datacenter or k8s <> non-k8s apps setup). Initially I wanted to use Consul as a distributed KV backend and then I thought: while you're here already, why can't you act as my service mesh even if you duplicate what k8s does already on its own 🤓


Consul is still useful in a single k8s cluster because you get the following features:
* encryption between all service calls
* enforcement of which services can call others (think network policy)
* metrics for all services
* ability to set reliability rules such as retries, timeouts
* ability to do traffic routing

**Comment by lkysow** [comment]
Yes those would be good reasons. The only thing I was thinking was that the mesh is really good for service-to-service traffic but Vault already has some of the features mentioned: it already require TLS, it has its own auth model, it has its own metrics.

And then you will have additional complexities getting Vault to run with the sidecar since it's not like a regular service. For example the proxy will need to talk to it over https.
