### ISSUE TITLE
Consul service mesh and Vault with raft

### ISSUE THREAD

**Issue by revathyr13** [hashicorp/consul-k8s#880]
[vaultk1d.txt](https://github.com/hashicorp/consul-k8s/files/7618054/vaultk1d.txt)
Hello Team,

We have deployed consul service mesh in our k8 cluster which are deployed in  2 Different DCs.  Now we have requirement where we want to deploy vault with raft as storage in these DCs and want to connect between vault pods using consul service mesh.

For that I deployed vault in one K8 cluster [where service mesh is deployed] with connect inject true and transparent proxy.
Then created new headless services which connects directly to pod and synced that service to service mesh using consul.hashicorp.com/service-sync: "true". Attached the service yaml file. 

Vault pods

NAME                                        READY   STATUS    RESTARTS   AGE
vault-k1d-0                                 2/2     Running   0          51m
vault-k1d-1                                 1/2     Running   0          51m

First pods is initialised and working fine

The issue is adding the second pod to first one using consul DNS

/vault/userconfig/mvault-tls $ vault operator raft join -leader-ca-cert=@ca.crt -leader-client-cert=@tls.crt -leader-client-key=@tls.key https://vau
lt-k1d-0-internal-vault-hashicorp-master.service.k1d-k8s.XXXX:8400
Error joining the node to the Raft cluster: Error making API request.

URL: POST https://127.0.0.1:8400/v1/sys/storage/raft/join
Code: 500. Errors:

* failed to join raft cluster: failed to join any raft leader node
/vault/userconfig/mvault-tls $

Logs from second pod

2021-11-29T12:10:18.179Z [WARN]  core: join attempt failed: error="error during raft bootstrap init call: Put "https://vault-k1d-0-internal-vault-hashicorp-master.service.k1d-k8s.XXXX:8400/v1/sys/storage/raft/bootstrap/challenge": x509: certificate is not valid for any names, but wanted to match vault-k1d-0-internal-vault-hashicorp-master.service.k1d-k8s.XXXXX"
2021-11-29T12:10:18.179Z [ERROR] core: failed to join raft cluster: error="failed to join any raft leader node"

Is there any way to inform consul servicemesh to use vault pod's certificate instead of mTLS?

**Comment by t-eckert** [comment]
Hi @revathyr13,

Thank you for reaching out about this issue. We will need some more details in order to reproduce and diagnose the bug. Can you please supply:

- How you deployed Vault and Consul.
- Which versions of Vault and Consul you are using.
- What is the DNS name you are using for the Vault operator join command? It looks like a Consul DNS name, but we want to clarify.

In general, we recommend operators not use Sync Catalog and Consul Service Mesh in one installation. This is because if two services have the same name, the Sync Catalog and Service Mesh will overwrite the services each one registers. Additionally, Consul DNS cannot be used at the same time as Transparent Proxy. When you are using Transparent Proxy, we rely on the virtual IP of the Kubernetes service. Consul DNS will not resolve to a virtual IP, nor will a headless service. The only way to make it route directly to pods is using the [dialed directly configuration](https://www.consul.io/docs/connect/transparent-proxy#headless-services).

**Comment by david-yu** [comment]
Hi @revathyr13 I hope the response from @t-eckert  was helpful. Will close now since we have not seen a response. If you do have more details that would be helpful.

**Comment by revathyr13** [comment]
Hello @t-eckert  ,

Sorry for the delayed response.

>How you deployed Vault and Consul and its versions 

Consul is deployed using https://github.com/hashicorp/consul-k8s/  helm chart in namespace called consul 
consul version is  consul-0.33.0 

Vault is deployed using  https://github.com/hashicorp/vault-helm helm chart and included following consul annotations and deployed in different namespace called   vault-hashicorp-master

 'consul.hashicorp.com/connect-inject': 'true'
    'consul.hashicorp.com/connect-service': 'vault-k1d'
    'consul.hashicorp.com/transparent-proxy': 'true'

Vault version is v1.7.3 

>What is the DNS name you are using for the Vault operator join command? It looks like a Consul DNS name, but we want to clarify
Yes i was using consul DNS.  So it wont work for pod to pod communication ? In case if service defaults  to be created in which namespace should it be created? in vault or consul ?  Once its created do i need to use pod ip for joining to vault ?

**Comment by revathyr13** [comment]
Also I have doubt  regarding transparent proxy. We have 2 kubernetes clusters in 2 different DC, where we want pod to pod communication between the vault pods . Does this can be achieved using transparent proxy feature of consul  ?

**Comment by blake** [comment]
Hi @revathyr13, transparent proxy currently only supports routing to destinations within the same DC. In order to connect to services residing in other DCs, you will need to use explicitly declared upstreams. See <https://www.consul.io/docs/connect/transparent-proxy#known-limitations> for more info.

**Comment by revathyr13** [comment]
Hello @blake  Thanks for the update. But if we use upstreams then we can connect only via locally right ? say, if vault service is connected via upstream from DC1 to another pod in DC dc2,  then we can only connect to it using localhost:8200 ? 
but it wont work as expected in case if we need pod to pod communication? Is there any method in consul service mesh to communicate between individual pods in 2 dcs ?

**Comment by blake** [comment]
> if vault service is connected via upstream from DC1 to another pod in DC dc2, then we can only connect to it using localhost:8200 ?

That is correct.

> but it wont work as expected in case if we need pod to pod communication? Is there any method in consul service mesh to communicate between individual pods in 2 dcs ?

I'm assuming you mean you need to directly communicate to each and every Vault instance in the the remote DC.

There's not currently a workaround to enable communicating directly with individual pods in a remote DC when using explicit upstreams. We are looking to address this limitation in a future release of Consul.
