### ISSUE TITLE
consul-connect-inject-init fail to start when with connectInject

### ISSUE THREAD

**Issue by hiberabyss** [hashicorp/consul-k8s#918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

When and following annotation, the pods failed to start.

```
consul.hashicorp.com/connect-inject: 'true'
```

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  name: consul
  datacenter: consul
server:
  storageClass: alicloud-disk-essd
  storage: 20Gi
ui:
  enabled: true
connectInject:
  enabled: true
```

### Logs

<details>
  <summary>Logs</summary>

```
➜  consul klog retrieval-blue-67c547bc76-88g5t -c consul-connect-inject-init
2021-12-09T06:29:21.357Z [ERROR] Unable to get Agent services: error="Get "http://172.16.68.119:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22retrieval-blue-67c
547bc76-88g5t%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22adsystem%22": dial tcp 172.16.68.119:8500: connect: connection refused"
2021-12-09T06:29:22.358Z [ERROR] Unable to get Agent services: error="Get "http://172.16.68.119:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22retrieval-blue-67c
547bc76-88g5t%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22adsystem%22": dial tcp 172.16.68.119:8500: connect: connection refused"
2021-12-09T06:29:23.359Z [ERROR] Unable to get Agent services: error="Get "http://172.16.68.119:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22retrieval-blue-67c
547bc76-88g5t%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22adsystem%22": dial tcp 172.16.68.119:8500: connect: connection refused"
2021-12-09T06:29:24.360Z [ERROR] Unable to get Agent services: error="Get "http://172.16.68.119:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22retrieval-blue-67c
547bc76-88g5t%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22adsystem%22": dial tcp 172.16.68.119:8500: connect: connection refused"
2021-12-09T06:29:25.361Z [ERROR] Unable to get Agent services: error="Get "http://172.16.68.119:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22retrieval-blue-67c
547bc76-88g5t%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22adsystem%22": dial tcp 172.16.68.119:8500: connect: connection refused"
2021-12-09T06:29:26.361Z [ERROR] Unable to get Agent services: error="Get "http://172.16.68.119:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22retrieval-blue-67c
547bc76-88g5t%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22adsystem%22": dial tcp 172.16.68.119:8500: connect: connection refused"
```

</details>

### Environment details

1. consul-k8s version:
```
consul  consul          1               2021-12-09 14:26:31.313605 +0800 CST    deployed        consul-0.37.0   1.10.4
```
2. k8s version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-aliyun.1", GitCommit:"66492d8", GitTreeState:"", BuildDate:"2021-08-23T11:21:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
3. Aliyun Cloud

**Comment by hiberabyss** [comment]
Seems aliyun did not support hostPort. Could it possible to use consul agent pod ip and port?

**Comment by ndhanushkodi** [comment]
Is `172.16.68.119` a K8s node/host ip? Currently at least some components such as endpoints controller, which registers the services with Consul uses the [host ip + host port on the client agent to register the service](https://github.com/hashicorp/consul-k8s/blob/main/control-plane/connect-inject/endpoints_controller.go#L214-L220), and the `connect-init` command, which is where your error is coming from, also uses the [host ip](https://github.com/hashicorp/consul-k8s/blob/main/control-plane/connect-inject/container_init.go#L322) for checking for the service registration.

This could potentially be a feature request to use the pod ip and port rather than host ip and port when talking to consul agents, but is currently unsupported.

**Comment by ishustava** [comment]
Hey @hiberabyss 

I don't think it'd be possible for us to use pod IP. We always need to register with the node-local agent and also configure Envoy to talk to the consul agent that is on the same node as the application, and using the node ip is the only way to ensure that it happens. 

As far as I know, there isn't a straightforward way for us to figure out the pod IP of the node-local agent running as a daemonset in Kubernetes (https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods). This then becomes even more complicated when the agent on the node is restarted and the agent's pod IP changes. The application then would have no way of knowing that updated IP since that configuration is only created at startup.

For those reasons, we currently require hostPort for the consul service mesh to run.

Having said that, we definitely don't think that host port is ideal. There are other clouds that don't support for one or another reason. We are looking at other ways to not require it anymore, but at this time we probably won't invest in making that communication possible via pod IPs.

Hope this makes sense!

I'm going to close this issue for now, but please let me know if there's anything I missed.
